sonar.projectKey=library-management-system
sonar.projectName=Library Management System Java
sonar.projectVersion=1.0
sonar.sources=Project/src/LMS
sonar.java.binaries=Project/build/classes
sonar.host.url=http://localhost:9000
sonar.token=sqa_0f8be39948d3765a78f1ef57209b286aa046fb2a